CREATE OR REPLACE DATABASE SYNTHEA;
CREATE OR REPLACE SCHEMA SYNTHEA;
CREATE STAGE SYNTHEA.SYNTHEA.SYNTHEA  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE OR REPLACE TABLE SYNTHEA.SYNTHEA.ALLERGIES as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.ALLERGIES;
CREATE OR REPLACE TABLE SYNTHEA.SYNTHEA.CAREPLANS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.CAREPLANS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.CLAIMS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.CLAIMS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.CLAIMS_TRANSACTIONS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.CLAIMS_TRANSACTIONS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.CONDITIONS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.CONDITIONS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.DEVICES as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.DEVICES;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.ENCOUNTERS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.ENCOUNTERS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.IMAGING_STUDIES as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.IMAGING_STUDIES;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.IMMUNIZATIONS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.IMMUNIZATIONS;
CREATE OR REPLACE  TABLE SYNTHEA.SYNTHEA.MEDICATIONS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.MEDICATIONS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.OBSERVATIONS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.OBSERVATIONS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.ORGANIZATIONS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.ORGANIZATIONS;
CREATE OR REPLACE  TABLE SYNTHEA.SYNTHEA.PATIENTS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.PATIENTS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.PAYERS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.PAYERS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.PAYER_TRANSITIONS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.PAYER_TRANSITIONS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.PROCEDURES as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.PROCEDURES;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.PROVIDERS as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.PROVIDERS;
CREATE  OR REPLACE TABLE SYNTHEA.SYNTHEA.SUPPLIES as select * from SYNTHEA_5000_SHARE_READONLY.SYNTHEA.SUPPLIES;

