-- Synthea Cortex Search Services Creation Script
-- This script creates Cortex Search Services for all TEXT columns in the SYNTHEA.SYNTHEA schema
-- Generated for synthetic healthcare data analysis

-- Set context
USE DATABASE SYNTHEA;
USE SCHEMA SYNTHEA;

-- PATIENTS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_SSN
ON SSN
ATTRIBUTES SSN
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SSN
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Drivers
ON DRIVERS
ATTRIBUTES DRIVERS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DRIVERS
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Passport
ON PASSPORT
ATTRIBUTES PASSPORT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PASSPORT
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Prefix
ON PREFIX
ATTRIBUTES PREFIX
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PREFIX
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_First
ON FIRST
ATTRIBUTES FIRST
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT FIRST
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Middle
ON MIDDLE
ATTRIBUTES MIDDLE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MIDDLE
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Last
ON LAST
ATTRIBUTES LAST
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT LAST
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Suffix
ON SUFFIX
ATTRIBUTES SUFFIX
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SUFFIX
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Maiden
ON MAIDEN
ATTRIBUTES MAIDEN
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MAIDEN
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Marital
ON MARITAL
ATTRIBUTES MARITAL
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MARITAL
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Race
ON RACE
ATTRIBUTES RACE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT RACE
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Ethnicity
ON ETHNICITY
ATTRIBUTES ETHNICITY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ETHNICITY
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Gender
ON GENDER
ATTRIBUTES GENDER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT GENDER
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Birthplace
ON BIRTHPLACE
ATTRIBUTES BIRTHPLACE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT BIRTHPLACE
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Address
ON ADDRESS
ATTRIBUTES ADDRESS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ADDRESS
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_City
ON CITY
ATTRIBUTES CITY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CITY
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_State
ON STATE
ATTRIBUTES STATE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STATE
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_County
ON COUNTY
ATTRIBUTES COUNTY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT COUNTY
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Fips
ON FIPS
ATTRIBUTES FIPS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT FIPS
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Patients_Zip
ON ZIP
ATTRIBUTES ZIP
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ZIP
    FROM "SYNTHEA"."SYNTHEA"."PATIENTS"
);

-- ORGANIZATIONS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Organizations_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."ORGANIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Organizations_Name
ON NAME
ATTRIBUTES NAME
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT NAME
    FROM "SYNTHEA"."SYNTHEA"."ORGANIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Organizations_Address
ON ADDRESS
ATTRIBUTES ADDRESS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ADDRESS
    FROM "SYNTHEA"."SYNTHEA"."ORGANIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Organizations_City
ON CITY
ATTRIBUTES CITY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CITY
    FROM "SYNTHEA"."SYNTHEA"."ORGANIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Organizations_State
ON STATE
ATTRIBUTES STATE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STATE
    FROM "SYNTHEA"."SYNTHEA"."ORGANIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Organizations_Phone
ON PHONE
ATTRIBUTES PHONE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PHONE
    FROM "SYNTHEA"."SYNTHEA"."ORGANIZATIONS"
);

-- PROVIDERS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_Organisation
ON ORGANISATION
ATTRIBUTES ORGANISATION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ORGANISATION
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_Name
ON NAME
ATTRIBUTES NAME
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT NAME
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_Gender
ON GENDER
ATTRIBUTES GENDER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT GENDER
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_Speciality
ON SPECIALITY
ATTRIBUTES SPECIALITY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SPECIALITY
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_Address
ON ADDRESS
ATTRIBUTES ADDRESS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ADDRESS
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_City
ON CITY
ATTRIBUTES CITY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CITY
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Providers_State
ON STATE
ATTRIBUTES STATE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STATE
    FROM "SYNTHEA"."SYNTHEA"."PROVIDERS"
);

-- PAYERS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_Name
ON NAME
ATTRIBUTES NAME
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT NAME
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_Ownership
ON OWNERSHIP
ATTRIBUTES OWNERSHIP
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT OWNERSHIP
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_Address
ON ADDRESS
ATTRIBUTES ADDRESS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ADDRESS
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_City
ON CITY
ATTRIBUTES CITY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CITY
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_State_Headquartered
ON STATE_HEADQUARTERED
ATTRIBUTES STATE_HEADQUARTERED
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STATE_HEADQUARTERED
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_Zip
ON ZIP
ATTRIBUTES ZIP
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ZIP
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payers_Phone
ON PHONE
ATTRIBUTES PHONE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PHONE
    FROM "SYNTHEA"."SYNTHEA"."PAYERS"
);

-- ENCOUNTERS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Organisation
ON ORGANISATION
ATTRIBUTES ORGANISATION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ORGANISATION
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Provider
ON PROVIDER
ATTRIBUTES PROVIDER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDER
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Payer
ON PAYER
ATTRIBUTES PAYER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PAYER
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Encounterclass
ON ENCOUNTERCLASS
ATTRIBUTES ENCOUNTERCLASS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTERCLASS
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Reasoncode
ON REASONCODE
ATTRIBUTES REASONCODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REASONCODE
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Encounters_Reasondescription
ON REASONDESCRIPTION
ATTRIBUTES REASONDESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REASONDESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."ENCOUNTERS"
);

-- CONDITIONS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Conditions_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."CONDITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Conditions_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."CONDITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Conditions_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."CONDITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Conditions_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."CONDITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Conditions_System
ON SYSTEM
ATTRIBUTES SYSTEM
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SYSTEM
    FROM "SYNTHEA"."SYNTHEA"."CONDITIONS"
);

-- OBSERVATIONS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Category
ON CATEGORY
ATTRIBUTES CATEGORY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CATEGORY
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Value
ON VALUE
ATTRIBUTES VALUE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT VALUE
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Units
ON UNITS
ATTRIBUTES UNITS
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT UNITS
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Observations_Type
ON TYPE
ATTRIBUTES TYPE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TYPE
    FROM "SYNTHEA"."SYNTHEA"."OBSERVATIONS"
);

-- PROCEDURES Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Procedures_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."PROCEDURES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Procedures_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."PROCEDURES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Procedures_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."PROCEDURES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Procedures_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."PROCEDURES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Procedures_Reasondescription
ON REASONDESCRIPTION
ATTRIBUTES REASONDESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REASONDESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."PROCEDURES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Procedures_System
ON SYSTEM
ATTRIBUTES SYSTEM
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SYSTEM
    FROM "SYNTHEA"."SYNTHEA"."PROCEDURES"
);

-- MEDICATIONS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Medications_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."MEDICATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Medications_Payer
ON PAYER
ATTRIBUTES PAYER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PAYER
    FROM "SYNTHEA"."SYNTHEA"."MEDICATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Medications_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."MEDICATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Medications_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."MEDICATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Medications_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."MEDICATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Medications_Reasoncode
ON REASONCODE
ATTRIBUTES REASONCODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REASONCODE
    FROM "SYNTHEA"."SYNTHEA"."MEDICATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Medications_Reasondescription
ON REASONDESCRIPTION
ATTRIBUTES REASONDESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REASONDESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."MEDICATIONS"
);

-- IMMUNIZATIONS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Immunizations_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."IMMUNIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Immunizations_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."IMMUNIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Immunizations_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."IMMUNIZATIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Immunizations_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."IMMUNIZATIONS"
);

-- ALLERGIES Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_System
ON SYSTEM
ATTRIBUTES SYSTEM
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SYSTEM
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Type
ON TYPE
ATTRIBUTES TYPE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TYPE
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Category
ON CATEGORY
ATTRIBUTES CATEGORY
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CATEGORY
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Description1
ON DESCRIPTION1
ATTRIBUTES DESCRIPTION1
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION1
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Severity1
ON SEVERITY1
ATTRIBUTES SEVERITY1
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SEVERITY1
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Description2
ON DESCRIPTION2
ATTRIBUTES DESCRIPTION2
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION2
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Severity2
ON SEVERITY2
ATTRIBUTES SEVERITY2
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SEVERITY2
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Allergies_Stop_Time
ON STOP_TIME
ATTRIBUTES STOP_TIME
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STOP_TIME
    FROM "SYNTHEA"."SYNTHEA"."ALLERGIES"
);

-- CAREPLANS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Careplans_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."CAREPLANS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Careplans_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."CAREPLANS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Careplans_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."CAREPLANS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Careplans_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."CAREPLANS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Careplans_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."CAREPLANS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Careplans_Reasoncode
ON REASONCODE
ATTRIBUTES REASONCODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REASONCODE
    FROM "SYNTHEA"."SYNTHEA"."CAREPLANS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Careplans_Reasondescription
ON REASONDESCRIPTION
ATTRIBUTES REASONDESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REASONDESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."CAREPLANS"
);

-- DEVICES Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Devices_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."DEVICES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Devices_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."DEVICES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Devices_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."DEVICES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Devices_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."DEVICES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Devices_UDI
ON UDI
ATTRIBUTES UDI
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT UDI
    FROM "SYNTHEA"."SYNTHEA"."DEVICES"
);

-- SUPPLIES Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Supplies_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."SUPPLIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Supplies_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."SUPPLIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Supplies_Code
ON CODE
ATTRIBUTES CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CODE
    FROM "SYNTHEA"."SYNTHEA"."SUPPLIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Supplies_Description
ON DESCRIPTION
ATTRIBUTES DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."SUPPLIES"
);

-- IMAGING_STUDIES Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_Encounter
ON ENCOUNTER
ATTRIBUTES ENCOUNTER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ENCOUNTER
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_Series_UID
ON SERIES_UID
ATTRIBUTES SERIES_UID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SERIES_UID
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_Bodysite_Description
ON BODYSITE_DESCRIPTION
ATTRIBUTES BODYSITE_DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT BODYSITE_DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_Modality_Code
ON MODALITY_CODE
ATTRIBUTES MODALITY_CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MODALITY_CODE
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_Modality_Description
ON MODALITY_DESCRIPTION
ATTRIBUTES MODALITY_DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MODALITY_DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_Instance_UID
ON INSTANCE_UID
ATTRIBUTES INSTANCE_UID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT INSTANCE_UID
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_SOP_Code
ON SOP_CODE
ATTRIBUTES SOP_CODE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SOP_CODE
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Imaging_Studies_SOP_Description
ON SOP_DESCRIPTION
ATTRIBUTES SOP_DESCRIPTION
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SOP_DESCRIPTION
    FROM "SYNTHEA"."SYNTHEA"."IMAGING_STUDIES"
);

-- PAYER_TRANSITIONS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payer_Transitions_Patient
ON PATIENT
ATTRIBUTES PATIENT
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENT
    FROM "SYNTHEA"."SYNTHEA"."PAYER_TRANSITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payer_Transitions_Memberid
ON MEMBERID
ATTRIBUTES MEMBERID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MEMBERID
    FROM "SYNTHEA"."SYNTHEA"."PAYER_TRANSITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payer_Transitions_Payer
ON PAYER
ATTRIBUTES PAYER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PAYER
    FROM "SYNTHEA"."SYNTHEA"."PAYER_TRANSITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payer_Transitions_Secondary_Payer
ON SECONDARY_PAYER
ATTRIBUTES SECONDARY_PAYER
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SECONDARY_PAYER
    FROM "SYNTHEA"."SYNTHEA"."PAYER_TRANSITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payer_Transitions_Plan_Ownership
ON PLAN_OWNERSHIP
ATTRIBUTES PLAN_OWNERSHIP
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PLAN_OWNERSHIP
    FROM "SYNTHEA"."SYNTHEA"."PAYER_TRANSITIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Payer_Transitions_Owner_Name
ON OWNER_NAME
ATTRIBUTES OWNER_NAME
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT OWNER_NAME
    FROM "SYNTHEA"."SYNTHEA"."PAYER_TRANSITIONS"
);

-- CLAIMS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Patientid
ON PATIENTID
ATTRIBUTES PATIENTID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENTID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Providerid
ON PROVIDERID
ATTRIBUTES PROVIDERID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDERID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Primarypatientinsuranceid
ON PRIMARYPATIENTINSURANCEID
ATTRIBUTES PRIMARYPATIENTINSURANCEID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PRIMARYPATIENTINSURANCEID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Secondarypatientinsuranceid
ON SECONDARYPATIENTINSURANCEID
ATTRIBUTES SECONDARYPATIENTINSURANCEID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SECONDARYPATIENTINSURANCEID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Referringproviderid
ON REFERRINGPROVIDERID
ATTRIBUTES REFERRINGPROVIDERID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT REFERRINGPROVIDERID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Appointmentid
ON APPOINTMENTID
ATTRIBUTES APPOINTMENTID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT APPOINTMENTID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Supervisingproviderid
ON SUPERVISINGPROVIDERID
ATTRIBUTES SUPERVISINGPROVIDERID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SUPERVISINGPROVIDERID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Status1
ON STATUS1
ATTRIBUTES STATUS1
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STATUS1
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Status2
ON STATUS2
ATTRIBUTES STATUS2
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STATUS2
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Statusp
ON STATUSP
ATTRIBUTES STATUSP
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT STATUSP
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS"
);

-- CLAIMS_TRANSACTIONS Table Search Services
CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_ID
ON ID
ATTRIBUTES ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT ID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Claimid
ON CLAIMID
ATTRIBUTES CLAIMID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT CLAIMID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Patientid
ON PATIENTID
ATTRIBUTES PATIENTID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENTID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Type
ON TYPE
ATTRIBUTES TYPE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TYPE
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Method
ON METHOD
ATTRIBUTES METHOD
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT METHOD
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Placeofservice
ON PLACEOFSERVICE
ATTRIBUTES PLACEOFSERVICE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PLACEOFSERVICE
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Modifier1
ON MODIFIER1
ATTRIBUTES MODIFIER1
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MODIFIER1
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Modifier2
ON MODIFIER2
ATTRIBUTES MODIFIER2
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT MODIFIER2
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Appointmentid
ON APPOINTMENTID
ATTRIBUTES APPOINTMENTID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT APPOINTMENTID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Linenote
ON LINENOTE
ATTRIBUTES LINENOTE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT LINENOTE
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Patientinsuranceid
ON PATIENTINSURANCEID
ATTRIBUTES PATIENTINSURANCEID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PATIENTINSURANCEID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Providerid
ON PROVIDERID
ATTRIBUTES PROVIDERID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT PROVIDERID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Supervisingproviderid
ON SUPERVISINGPROVIDERID
ATTRIBUTES SUPERVISINGPROVIDERID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT SUPERVISINGPROVIDERID
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Notes
ON NOTES
ATTRIBUTES NOTES
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT NOTES
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

CREATE OR REPLACE CORTEX SEARCH SERVICE Search_Synthea_Claims_Transactions_Transfertype
ON TRANSFERTYPE
ATTRIBUTES TRANSFERTYPE
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '1 day'
INITIALIZE = ON_SCHEDULE
AS (
    SELECT TRANSFERTYPE
    FROM "SYNTHEA"."SYNTHEA"."CLAIMS_TRANSACTIONS"
);

-- Script completed successfully
-- All Cortex Search Services for TEXT columns in Synthea tables have been created 