-- =====================================================
-- SUSPEND ALL CORTEX SEARCH SERVICES (FOR LATER USE)
-- =====================================================
-- ⚠️  WARNING: This script will suspend ALL Cortex Search services
-- ⚠️  Services will stop consuming SERVING credits but become unqueryable
-- ⚠️  Only run this if you want to completely stop serving costs
--
-- Expected Impact: 90%+ reduction in AI services costs (from ~117 credits/day to ~0)
-- Use Case: Emergency cost reduction or when demos are not needed for extended periods
-- 
-- To resume services later, change "SUSPENDED" to "RUNNING" in individual ALTER statements
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- =====================================================
-- IMPORTANT: BACKUP QUERY TO RESUME SERVICES LATER
-- =====================================================
/*
-- To resume specific services for demos, use these templates:
-- ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID SET SERVING_STATE = RUNNING;
-- ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTID SET SERVING_STATE = RUNNING;
-- ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ENTITY_NO SET SERVING_STATE = RUNNING;
*/

-- CODES Database (1 service)
ALTER CORTEX SEARCH SERVICE CODES.CODES.CODES_SEARCH_SERVICE RESUME;

-- HEALTHCARE_DEMO Database (1 service) 
ALTER CORTEX SEARCH SERVICE HEALTHCARE_DEMO.MEDICAL_NOTES.PATIENT_SEARCH_SERVICE RESUME;

-- PMC_PATIENTS Database (1 service)
ALTER CORTEX SEARCH SERVICE PMC_PATIENTS.PMC_PATIENTS.PATIENTS_SEARCH RESUME;
/*
-- QUANTIUM_DEMO Database (30 services) - Minimal cost impact
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_ARTICLE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_ARTICLE_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_BRAND RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_BRAND_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_CATEGORY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_CATEGORY_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_DEPARTMENT RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_DEPARTMENT_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_SALES_UNIT RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_SUBCATEGORY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_SUBCATEGORY_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VENDOR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VENDOR_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VN_VENDOR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VN_VENDOR_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_AREA RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_AREA_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_CITY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_COUNTRY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_COUNTRY_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_REGION RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_REGION_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SALES_DISTRICT RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SALES_DISTRICT_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SITE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SITE_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_STATE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_STATE_DESC RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_ZONE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_ZONE_DESC RESUME;

-- QUANTIUM_HEALTHCARE_DEMO Database (93 services) - HIGH COST IMPACT: ~22.96 credits/day
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_CODE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_2 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_3 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_4 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_5 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_GEOGRAPHY_COUNTRY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_GEOGRAPHY_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_GEOGRAPHY_REGION RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_MEDICAL_SCHEMES_PLAN_GROUP RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_MEDICAL_SCHEMES_PLAN_TYPE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_MEDICAL_SCHEMES_SCHEME_NAME RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_AGE_BUCKET RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_AGE_GROUPS RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_ENTITY_NO RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_GENDER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_REGION_OF_RESIDENCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_ATC_CODE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_DOSAGE_FORM RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_NAPPI_MANUFACTURER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_PRODUCT_NAME RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_STRENGTH RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_ALL_LEVELS_CONCAT RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_ALL_LEVELS_CONCAT_4 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_2 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_3 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_4 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_LEVELS_CONCAT_TILL_2 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_MANUFACTURER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_TR_LEVEL_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_CATEGORY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_GROUP RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_NAME RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_TYPE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_REGION RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_ALL_LEVELS_CONCAT RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_ALL_LEVELS_CONCAT_4 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_CATEGORY_DESCR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_2 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_3 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_4 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_LEVELS_CONCAT_TILL_2 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_MANUFACTURER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_PRACTICE_NO_DESCR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_PROVIDER_GROUP RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_PROVINCE_DESCR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_P_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_TR_LEVEL_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HIGH_VALUE_CLAIMS_RISK_RISK_CATEGORY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_AGE_GROUPS RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_COST_CATEGORY RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_ENTITY_NO RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_AGE_BUCKET RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_AGE_GROUPS RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_2 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_3 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_4 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_5 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_BUCKET RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_DEG_DESCR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_DOSAGE_FORM RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ENTITY_NO RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_GENDER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_NAPPI_MANUFACTURER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PLAN_GRP RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PLAN_SCHEME RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PRODUCT_NAME RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_GROUP RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_REGION RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_TYPE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_REGION_OF_RESIDENCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_STRENGTH RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_TREATING_DR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_TR_PROCEDURE_CODE_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_CLAIMS_SUMMARY_CATEGORY_DESCR RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_CLAIMS_SUMMARY_P_PROVINCE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_CLAIMS_SUMMARY_TR_LEVEL_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_AGE_GROUPS RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_ATC_LEVEL_DESC_1 RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_GENDER RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_PROVIDER_TYPE RESUME;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_PROVINCE RESUME;
*/



-- SALES_INTELLIGENCE Database (1 service)
ALTER CORTEX SEARCH SERVICE SALES_INTELLIGENCE.DATA.SALES_CONVERSATION_SEARCH RESUME;

-- SYNTHEA Database (153 services) - HIGHEST COST IMPACT: ~94.52 credits/day
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_CATEGORY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_DESCRIPTION1 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_DESCRIPTION2 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_SEVERITY1 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_SEVERITY2 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_STOP_TIME RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_SYSTEM RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_TYPE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_REASONCODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_REASONDESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_APPOINTMENTID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_PATIENTID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_PRIMARYPATIENTINSURANCEID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_PROVIDERID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_REFERRINGPROVIDERID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_SECONDARYPATIENTINSURANCEID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_STATUS1 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_STATUS2 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_STATUSP RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_SUPERVISINGPROVIDERID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_APPOINTMENTID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_CLAIMID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_LINENOTE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_METHOD RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_MODIFIER1 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_MODIFIER2 RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_NOTES RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTINSURANCEID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PLACEOFSERVICE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PROVIDERID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_SUPERVISINGPROVIDERID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_TRANSFERTYPE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_TYPE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_SYSTEM RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_UDI RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_ENCOUNTERCLASS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_ORGANISATION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_PAYER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_PROVIDER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_REASONCODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_REASONDESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_BODYSITE_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_INSTANCE_UID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_MODALITY_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_MODALITY_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_SERIES_UID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_SOP_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_SOP_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_PAYER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_REASONCODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_REASONDESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_CATEGORY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_TYPE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_UNITS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_VALUE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_ADDRESS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_CITY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_NAME RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_PHONE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_STATE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ADDRESS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_BIRTHPLACE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_CITY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_COUNTY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_DRIVERS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ETHNICITY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIPS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIRST RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_GENDER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_LAST RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_MAIDEN RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_MARITAL RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_MIDDLE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_PASSPORT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_PREFIX RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_RACE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_SSN RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_STATE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_SUFFIX RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ZIP RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_ADDRESS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_CITY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_NAME RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_OWNERSHIP RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_PHONE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_STATE_HEADQUARTERED RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_ZIP RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_MEMBERID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_OWNER_NAME RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_PAYER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_PLAN_OWNERSHIP RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_SECONDARY_PAYER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_PATIENT RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_REASONDESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_SYSTEM RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_ADDRESS RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_CITY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_GENDER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_NAME RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_ORGANISATION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_SPECIALITY RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_STATE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_CODE RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_ENCOUNTER RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_PATIENT RESUME;

-- =====================================================
-- SUMMARY OF SUSPENDED SERVICES
-- =====================================================
SELECT 
    'Successfully resumed ' || COUNT(*) || ' Cortex Search services across ' || COUNT(DISTINCT database_name) || ' databases' as summary
FROM (
    SELECT DISTINCT 
        database_name, 
        schema_name, 
        service_name
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY 
    WHERE usage_date >= CURRENT_DATE - 3
);

-- =====================================================
-- DEMO RESUME TEMPLATES (Copy and customize as needed)
-- =====================================================
/*
-- Template: Resume key services for SYNTHEA demos
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIRST SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_LAST SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTID SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_DESCRIPTION SET SERVING_STATE = RUNNING;

-- Template: Resume key services for QUANTIUM_HEALTHCARE_DEMO
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ENTITY_NO SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PRODUCT_NAME SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_ENTITY_NO SET SERVING_STATE = RUNNING;
*/

-- =====================================================
-- POST-DEMO CLEANUP TEMPLATE (Re-suspend after demos)
-- =====================================================
/*
-- Re-suspend demo services after demo completion
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIRST RESUME;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_LAST RESUME;
-- ... add other services as needed
*/
