-- =====================================================
-- SUSPEND ALL CORTEX SEARCH SERVICES (FOR LATER USE)
-- =====================================================
-- ⚠️  WARNING: This script will suspend ALL Cortex Search services
-- ⚠️  Services will stop consuming SERVING credits but become unqueryable
-- ⚠️  Only run this if you want to completely stop serving costs
--
-- Expected Impact: 90%+ reduction in AI services costs (from ~117 credits/day to ~0)
-- Use Case: Emergency cost reduction or when demos are not needed for extended periods
-- 
-- To resume services later, change "SUSPENDED" to "RUNNING" in individual ALTER statements
-- =====================================================

USE ROLE ACCOUNTADMIN;

-- =====================================================
-- IMPORTANT: BACKUP QUERY TO RESUME SERVICES LATER
-- =====================================================
/*
-- To resume specific services for demos, use these templates:
-- ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID SET SERVING_STATE = RUNNING;
-- ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTID SET SERVING_STATE = RUNNING;
-- ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ENTITY_NO SET SERVING_STATE = RUNNING;
*/

-- CODES Database (1 service)
ALTER CORTEX SEARCH SERVICE CODES.CODES.CODES_SEARCH_SERVICE SUSPEND; -- RESUME;;

-- HEALTHCARE_DEMO Database (1 service) 
ALTER CORTEX SEARCH SERVICE HEALTHCARE_DEMO.MEDICAL_NOTES.PATIENT_SEARCH_SERVICE SUSPEND; -- RESUME;;

-- PMC_PATIENTS Database (1 service)
ALTER CORTEX SEARCH SERVICE PMC_PATIENTS.PMC_PATIENTS.PATIENTS_SEARCH SUSPEND; -- RESUME;;

-- QUANTIUM_DEMO Database (30 services) - Minimal cost impact
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_ARTICLE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_ARTICLE_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_BRAND SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_BRAND_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_CATEGORY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_CATEGORY_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_DEPARTMENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_DEPARTMENT_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_SALES_UNIT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_SUBCATEGORY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_SUBCATEGORY_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VENDOR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VENDOR_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VN_VENDOR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_PROD_VN_VENDOR_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_AREA SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_AREA_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_CITY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_COUNTRY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_COUNTRY_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_REGION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_REGION_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SALES_DISTRICT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SALES_DISTRICT_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SITE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_SITE_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_STATE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_STATE_DESC SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_ZONE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_DEMO.TEXT2SQL.SEARCH_QUANTIUM_SITE_ZONE_DESC SUSPEND; -- RESUME;;

-- QUANTIUM_HEALTHCARE_DEMO Database (93 services) - HIGH COST IMPACT: ~22.96 credits/day
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_3 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_4 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_ATC_HIERARCHY_ATC_LEVEL_DESC_5 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_GEOGRAPHY_COUNTRY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_GEOGRAPHY_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_GEOGRAPHY_REGION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_MEDICAL_SCHEMES_PLAN_GROUP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_MEDICAL_SCHEMES_PLAN_TYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_MEDICAL_SCHEMES_SCHEME_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_AGE_BUCKET SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_AGE_GROUPS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_ENTITY_NO SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_GENDER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_REGION_OF_RESIDENCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_ATC_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_DOSAGE_FORM SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_NAPPI_MANUFACTURER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_PRODUCT_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PHARMACEUTICALS_STRENGTH SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_ALL_LEVELS_CONCAT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_ALL_LEVELS_CONCAT_4 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_3 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_HIGH_LEVEL_4 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_LEVELS_CONCAT_TILL_2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_MANUFACTURER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PRODUCTS_TR_LEVEL_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_CATEGORY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_GROUP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVIDER_TYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PROVIDERS_REGION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_ALL_LEVELS_CONCAT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_ALL_LEVELS_CONCAT_4 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_CATEGORY_DESCR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_3 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_HIGH_LEVEL_4 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_LEVELS_CONCAT_TILL_2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_MANUFACTURER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_PRACTICE_NO_DESCR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_PROVIDER_GROUP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_PROVINCE_DESCR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_P_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HEALTHCARE_CLAIMS_TR_LEVEL_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_HIGH_VALUE_CLAIMS_RISK_RISK_CATEGORY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_AGE_GROUPS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_COST_CATEGORY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_ENTITY_NO SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PATIENT_COST_CATEGORIES_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_AGE_BUCKET SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_AGE_GROUPS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_3 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_4 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ATC_LEVEL_DESC_5 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_BUCKET SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_DEG_DESCR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_DOSAGE_FORM SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ENTITY_NO SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_GENDER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_NAPPI_MANUFACTURER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PLAN_GRP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PLAN_SCHEME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PRODUCT_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_GROUP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_REGION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVIDER_TYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_REGION_OF_RESIDENCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_STRENGTH SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_TREATING_DR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_TR_PROCEDURE_CODE_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_CLAIMS_SUMMARY_CATEGORY_DESCR SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_CLAIMS_SUMMARY_P_PROVINCE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_CLAIMS_SUMMARY_TR_LEVEL_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_AGE_GROUPS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_ATC_LEVEL_DESC_1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_GENDER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_PROVIDER_TYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_VW_PHARMA_SUMMARY_PROVINCE SUSPEND; -- RESUME;;

-- SALES_INTELLIGENCE Database (1 service)
ALTER CORTEX SEARCH SERVICE SALES_INTELLIGENCE.DATA.SALES_CONVERSATION_SEARCH SUSPEND; -- RESUME;;

-- SYNTHEA Database (153 services) - HIGHEST COST IMPACT: ~94.52 credits/day
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_CATEGORY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_DESCRIPTION1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_DESCRIPTION2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_SEVERITY1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_SEVERITY2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_STOP_TIME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_SYSTEM SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ALLERGIES_TYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_REASONCODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CAREPLANS_REASONDESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_APPOINTMENTID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_PATIENTID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_PRIMARYPATIENTINSURANCEID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_PROVIDERID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_REFERRINGPROVIDERID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_SECONDARYPATIENTINSURANCEID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_STATUS1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_STATUS2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_STATUSP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_SUPERVISINGPROVIDERID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_APPOINTMENTID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_CLAIMID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_LINENOTE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_METHOD SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_MODIFIER1 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_MODIFIER2 SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_NOTES SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTINSURANCEID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PLACEOFSERVICE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PROVIDERID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_SUPERVISINGPROVIDERID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_TRANSFERTYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_TYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CONDITIONS_SYSTEM SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_DEVICES_UDI SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_ENCOUNTERCLASS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_ORGANISATION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_PAYER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_PROVIDER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_REASONCODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ENCOUNTERS_REASONDESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_BODYSITE_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_INSTANCE_UID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_MODALITY_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_MODALITY_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_SERIES_UID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_SOP_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMAGING_STUDIES_SOP_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_IMMUNIZATIONS_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_PAYER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_REASONCODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_MEDICATIONS_REASONDESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_CATEGORY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_TYPE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_UNITS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_VALUE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_ADDRESS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_CITY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_PHONE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_ORGANIZATIONS_STATE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ADDRESS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_BIRTHPLACE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_CITY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_COUNTY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_DRIVERS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ETHNICITY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIPS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIRST SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_GENDER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_LAST SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_MAIDEN SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_MARITAL SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_MIDDLE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_PASSPORT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_PREFIX SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_RACE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_SSN SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_STATE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_SUFFIX SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ZIP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_ADDRESS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_CITY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_OWNERSHIP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_PHONE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_STATE_HEADQUARTERED SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYERS_ZIP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_MEMBERID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_OWNER_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_PAYER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_PLAN_OWNERSHIP SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PAYER_TRANSITIONS_SECONDARY_PAYER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_PATIENT SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_REASONDESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROCEDURES_SYSTEM SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_ADDRESS SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_CITY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_GENDER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_NAME SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_ORGANISATION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_SPECIALITY SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PROVIDERS_STATE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_CODE SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_DESCRIPTION SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_ENCOUNTER SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_SUPPLIES_PATIENT SUSPEND; -- RESUME;;

-- =====================================================
-- SUMMARY OF SUSPENDED SERVICES
-- =====================================================
SELECT 
    'Successfully suspended ' || COUNT(*) || ' Cortex Search services across ' || COUNT(DISTINCT database_name) || ' databases' as summary
FROM (
    SELECT DISTINCT 
        database_name, 
        schema_name, 
        service_name
    FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_SEARCH_DAILY_USAGE_HISTORY 
    WHERE usage_date >= CURRENT_DATE - 3
);

-- =====================================================
-- DEMO RESUME TEMPLATES (Copy and customize as needed)
-- =====================================================
/*
-- Template: Resume key services for SYNTHEA demos
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIRST SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_LAST SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_CLAIMS_TRANSACTIONS_PATIENTID SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_OBSERVATIONS_DESCRIPTION SET SERVING_STATE = RUNNING;

-- Template: Resume key services for QUANTIUM_HEALTHCARE_DEMO
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_ENTITY_NO SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_PHARMACEUTICAL_CLAIMS_PRODUCT_NAME SET SERVING_STATE = RUNNING;
ALTER CORTEX SEARCH SERVICE QUANTIUM_HEALTHCARE_DEMO.QUANTIUM_HEALTHCARE_DEMO.SEARCH_QUAIL_DIM_PATIENTS_ENTITY_NO SET SERVING_STATE = RUNNING;
*/

-- =====================================================
-- POST-DEMO CLEANUP TEMPLATE (Re-suspend after demos)
-- =====================================================
/*
-- Re-suspend demo services after demo completion
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_ID SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_FIRST SUSPEND; -- RESUME;;
ALTER CORTEX SEARCH SERVICE SYNTHEA.SYNTHEA.SEARCH_SYNTHEA_PATIENTS_LAST SUSPEND; -- RESUME;;
-- ... add other services as needed
*/
